FROM devframe-centos

USER root

#RUN useradd -u 185 -G root webwas

#ADD files/apr-1.6.5.tar.gz /usr/local/
#ADD files/apr-util-1.6.1.tar.gz /usr/local/
#ADD files/httpd-2.4.37.tar.gz /usr/local/

#USER webwas

RUN yum install apache

CMD ["/bin/bash"]